name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: 'Region required'
        required: true
      

# env:
#   AWS_REGION: ap-south-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: module/

    - name: Terraform Format
      run: terraform fmt
      working-directory: module/

    - name: Terraform Plan
      run: terraform plan -var-file=manish.tfvars -out=tfplan
      working-directory: module/

    - name: Terraform Apply
      run: terraform apply -var-file="manish.tfvars" -auto-approve
      working-directory: module/
